---
- name: Ensure hostname is resolvable
  lineinfile:
    dest: /etc/hosts
    regexp: '^{{ ansible_default_ipv4.address }}'
    line: '{{ ansible_default_ipv4.address }} {{ ansible_nodename }} {{ ansible_hostname }}'
    state: present

- name: Ensure oraInst.loc
  template:
    src: oraInst.loc.j2
    dest: /etc/oraInst.loc
    owner: root
    group: root
    mode: '0644'
  when: '{{ oracle_setup_inventory | default(false) }}'

- name: Ensure Oracle Inventory
  file:
    name: '{{ oracle_inventory_directory }}'
    owner: '{{ oracle_db_owner_user_name }}'
    group: '{{ oracle_inventory_group_name }}'
    mode: '{{ oracle_inventory_directory_mode }}'
    state: directory
  when: '{{ oracle_setup_inventory | default(false) }}'
