---
- name: Ensure inventory group
  group:
    name: '{{ oracle_inventory_group_name }}'
    gid: '{{ oracle_inventory_group_id }}'
    state: present

- name: Ensure Grid Infrastructure groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  with_items: oracle_gi_os_groups
  when: oracle_role_separation|bool and oracle_setup_gi_os_groups

- name: Ensure Database groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  with_items: oracle_db_os_groups
  when: oracle_role_separation|bool and oracle_setup_db_os_groups

- name: Ensure Oracle Database groups (12c)
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  with_items: oracle_db_os_groups_12c
  when: oracle_role_separation|bool and oracle_setup_db12c_os_groups
