---
- name: Ensure inventory group
  group:
    name: '{{ oracle_inventory_group_name }}'
    gid: '{{ oracle_inventory_group_id }}'
    state: present

- name: Ensure Grid Infrastructure groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  with_items: oracle_gi_os_groups
  when: oracle_role_separation|bool and oracle_gi_homes is defined

- name: Ensure Database groups
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  with_items: oracle_db_os_groups
  when: oracle_role_separation|bool and oracle_db_home is defined

- name: Setting default value for fact oracle_db_homes_12c
  set_fact:
    oracle_db_homes_12c:  '{{ oracle_db_homes_12c or oracle_db_home.version[:2] | default(false) == "12" }}'
  when: oracle_db_home is defined

- name: Ensure Oracle Database groups (12c)
  group:
    name: '{{ item.name }}'
    gid: '{{ item.gid }}'
    state: present
  with_items: oracle_db_os_groups_12c
  when: oracle_role_separation|bool and oracle_db_homes_12c|bool
